### ISSUE TITLE
請求更新DM5-Viewer DM5漫站改版無法正常一次全部載入圖片。

### ISSUE THREAD

**Issue by ok3672108** [emma2334/DM5-Viewer#1]
請求更新DM5-Viewer DM5漫站改版無法正常一次全部載入圖片。

**Comment by emma2334** [comment]
我會在近期內修正的，謝謝通報

**Comment by ok3672108** [comment]
艾瑪 安 那個 可以的話能否支援 以下漫站 跟 動屋未改版之前 一樣的平台風格
http://tel.1kkk.com/manhua-list-size72/

**Comment by emma2334** [comment]
有空我再來研究研究，如果等不及的話也可以試試自己做一個，可以參考我的程式碼或是另一位大大寫的無限動漫腳本 ;-)

**Comment by ok3672108** [comment]
沒關係 我等好了 我對這程式 外行 看不懂

**Comment by emma2334** [comment]
問題已修正，日後我會再找時間補齊其他功能和寫另外一個網站的腳本

**Comment by ok3672108** [comment]
好的感恩 emma 辛苦製作的福利 謝謝

**Comment by ok3672108** [comment]
再次回報 DM5漫站好像 又有改版  DM5-Viewer  無法正常一次全部載入圖片

**Comment by emma2334** [comment]
現在這個腳本也支援 1kkk 了

**Comment by ok3672108** [comment]
非常感謝 可以 互補閱讀了 有時候 漫屋更新漫 可以先看1kkk 漫站
